name: ${name}
version: '1.0'
summary: An interactive web server.
description: |
  HTTPLab let you inspect HTTP requests and forge responses.

confinement: devmode
base: core18

parts:
  ${name}:
    plugin: go
    go-importpath: github.com/gchaincl/httplab
    source: https://github.com/gchaincl/httplab
    source-type: git
    build-packages:
      - gcc

apps:
  ${name}:
    command: bin/httplab
