name: ${name}
version: '1.8.1'
summary: |
  Application for Mind Mapping, Knowledge
  and Project Management
description: |
  Freeplane is a free and open source software
  application that supports thinking, sharing
  information and getting things done at work,
  in school and at home. The core of the
  software is tools for mind mapping (also known
  as concept mapping or information mapping)
  and using mapped information.

confinement: devmode
base: core18

parts:
  freeplane:
    plugin: gradle
    source: https://github.com/freeplane/freeplane.git
    source-tag: release-$SNAPCRAFT_PROJECT_VERSION
    gradle-version: '5.1.1'
    gradle-output-dir: BIN
    gradle-options: [binZip, -xtest, -xcreateGitTag]
    override-build: |
      snapcraftctl build
      unzip -o DIST/freeplane_bin-*.zip -d $SNAPCRAFT_PART_INSTALL/
    build-packages:
      - unzip

apps:
  ${name}:
    extensions:
      - gnome-3-28
    command: freeplane-$SNAPCRAFT_PROJECT_VERSION/freeplane.sh
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH
    plugs:
      - home
      - network
      - cups-control
