name: ${name}
version: '1.0'
summary: Command line weather tool.
description: |
  Get current weather:-
    $ wethr
  Get current weather in metric units
    $ wethr --metric
  Get current weather in imperial units
    $ wethr --imperial

confinement: devmode
base: core18

parts:
  ${name}:
    plugin: nodejs
    source: https://github.com/twobucks/wethr.git

apps:
  ${name}:
    command: wethr
