name: ${name}
version: '0.1'
summary: MOOS Example
description: |
  This example includes MOOSDB, the main communication mechanism for all MOOS
  apps.

confinement: devmode
base: core18

parts:
  ${name}:
    source: https://github.com/themoos/core-moos/archive/v10.4.0.tar.gz
    plugin: cmake
    build-packages: [g++]

apps:
  ${name}:
    command: bin/MOOSDB
